import type { Product } from '@/types';

export const PRODUCTS: Product[] = [
  {
    id: 'aurora-wrap-dress',
    name: 'Aurora Wrap Dress',
    brand: 'Zara',
    category: 'dresses',
    price: 128,
    colors: ['Ivory', 'Sage', 'Black'],
    image: 'https://images.pexels.com/photos/8311893/pexels-photo-8311893.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'A figure-flattering faux-wrap dress with a deep V neckline and an A-line skirt that skims the hips. Designed to define the waist while leaving room through the bust.',
    fit: 'Fitted at waist, relaxed through hips',
    material: '96% Rayon, 4% Spandex',
    fabricStretch: 'medium',
    fitStyle: 'fitted',
    sizeChart: {
      measurements: ['bust', 'waist', 'hips'],
      rows: [
        { size: 'XS', bust: 81, waist: 61, hips: 86 },
        { size: 'S', bust: 86, waist: 66, hips: 91 },
        { size: 'M', bust: 91, waist: 71, hips: 97 },
        { size: 'L', bust: 97, waist: 76, hips: 102 },
        { size: 'XL', bust: 102, waist: 81, hips: 107 },
      ],
    },
  },
  {
    id: 'marais-shift-dress',
    name: 'Marais Shift Dress',
    brand: 'H&M',
    category: 'dresses',
    price: 96,
    colors: ['Cherry', 'Navy'],
    image: 'https://images.pexels.com/photos/36594454/pexels-photo-36594454.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'An effortless shift dress that falls straight from the shoulder. Roomy through the waist and hips, so fit is driven mainly by bust and overall length.',
    fit: 'Relaxed, straight silhouette',
    material: '100% Polyester (crepe weave)',
    fabricStretch: 'none',
    fitStyle: 'relaxed',
    sizeChart: {
      measurements: ['bust', 'hips'],
      rows: [
        { size: 'XS', bust: 84, hips: 89 },
        { size: 'S', bust: 89, hips: 94 },
        { size: 'M', bust: 94, hips: 99 },
        { size: 'L', bust: 99, hips: 104 },
        { size: 'XL', bust: 104, hips: 109 },
      ],
    },
  },
  {
    id: 'rue-blouse',
    name: 'Rue Silk Blouse',
    brand: 'Zara',
    category: 'tops',
    price: 74,
    colors: ['White', 'Blush', 'Black'],
    image: 'https://images.pexels.com/photos/38801433/pexels-photo-38801433.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'A fluid silk blouse with a relaxed body and a classic point collar. Fit is determined primarily by bust; the waist and hem are intentionally easy.',
    fit: 'Relaxed through waist',
    material: '100% Mulberry silk',
    fabricStretch: 'none',
    fitStyle: 'relaxed',
    sizeChart: {
      measurements: ['bust'],
      rows: [
        { size: 'XS', bust: 84 },
        { size: 'S', bust: 89 },
        { size: 'M', bust: 94 },
        { size: 'L', bust: 99 },
        { size: 'XL', bust: 104 },
      ],
    },
  },
  {
    id: 'noe-crop-top',
    name: 'Noé Crop Top',
    brand: 'H&M',
    category: 'tops',
    price: 48,
    colors: ['Cream', 'Olive'],
    image: 'https://images.pexels.com/photos/9263790/pexels-photo-9263790.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'A structured crop top with boned seams that hugs the bust and waist. Because the bodice is fitted, both bust and waist drive the right size.',
    fit: 'Structured, fitted bodice',
    material: '62% Cotton, 33% Nylon, 5% Elastane',
    fabricStretch: 'high',
    fitStyle: 'fitted',
    sizeChart: {
      measurements: ['bust', 'waist'],
      rows: [
        { size: 'XS', bust: 81, waist: 61 },
        { size: 'S', bust: 86, waist: 66 },
        { size: 'M', bust: 91, waist: 71 },
        { size: 'L', bust: 97, waist: 76 },
        { size: 'XL', bust: 102, waist: 81 },
      ],
    },
  },
  {
    id: 'rive-skinny-jeans',
    name: 'Rive High-Rise Skinny Jeans',
    brand: 'Nike',
    category: 'jeans',
    price: 89,
    colors: ['Mid Wash', 'Black'],
    image: 'https://images.pexels.com/photos/17515363/pexels-photo-17515363.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'High-rise skinny jeans with powerful stretch. They contour the waist and hips and taper down the leg, so waist, hips, and inseam all matter.',
    fit: 'High-rise, skinny leg',
    material: '92% Cotton, 6% Polyester, 2% Elastane',
    fabricStretch: 'low',
    fitStyle: 'fitted',
    sizeChart: {
      measurements: ['waist', 'hips', 'inseam'],
      rows: [
        { size: 'XS', waist: 61, hips: 86, inseam: 71 },
        { size: 'S', waist: 66, hips: 91, inseam: 74 },
        { size: 'M', waist: 71, hips: 97, inseam: 76 },
        { size: 'L', waist: 76, hips: 102, inseam: 79 },
        { size: 'XL', waist: 81, hips: 107, inseam: 81 },
      ],
    },
  },
  {
    id: 'marais-wide-leg',
    name: 'Marais Wide-Leg Jeans',
    brand: 'Nike',
    category: 'jeans',
    price: 98,
    colors: ['Stonewash', 'Ecru'],
    image: 'https://images.pexels.com/photos/17720441/pexels-photo-17720441.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'A relaxed wide-leg jean with a straight waistband. The hip and inseam drive the fit; the wide leg leaves plenty of room below the hip.',
    fit: 'Relaxed hip, wide leg',
    material: '100% Cotton (no stretch)',
    fabricStretch: 'none',
    fitStyle: 'relaxed',
    sizeChart: {
      measurements: ['waist', 'hips', 'inseam'],
      rows: [
        { size: 'XS', waist: 64, hips: 89, inseam: 74 },
        { size: 'S', waist: 69, hips: 94, inseam: 76 },
        { size: 'M', waist: 74, hips: 99, inseam: 79 },
        { size: 'L', waist: 79, hips: 104, inseam: 81 },
        { size: 'XL', waist: 84, hips: 109, inseam: 84 },
      ],
    },
  },
  {
    id: 'loupe-a-line-skirt',
    name: 'Loupe A-Line Skirt',
    brand: 'Zara',
    category: 'skirts',
    price: 68,
    colors: ['Camel', 'Black'],
    image: 'https://images.pexels.com/photos/22819849/pexels-photo-22819849.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'A knee-grazing A-line skirt that sits at the natural waist. The waistband is the key measurement; the skirt flares gently over the hips.',
    fit: 'Natural waist, A-line flare',
    material: '98% Wool, 2% Elastane',
    fabricStretch: 'low',
    fitStyle: 'tailored',
    sizeChart: {
      measurements: ['waist', 'hips'],
      rows: [
        { size: 'XS', waist: 61, hips: 89 },
        { size: 'S', waist: 66, hips: 94 },
        { size: 'M', waist: 71, hips: 99 },
        { size: 'L', waist: 76, hips: 104 },
        { size: 'XL', waist: 81, hips: 109 },
      ],
    },
  },
  {
    id: 'centre-pleated-skirt',
    name: 'Centre Pleated Skirt',
    brand: 'H&M',
    category: 'skirts',
    price: 82,
    colors: ['Champagne', 'Navy'],
    image: 'https://images.pexels.com/photos/11530922/pexels-photo-11530922.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'A fully pleated midi skirt with an elasticated waistband. Because the waistband stretches, fit is driven mainly by the hips and desired length.',
    fit: 'Elastic waist, pleated body',
    material: '100% Polyester satin',
    fabricStretch: 'medium',
    fitStyle: 'relaxed',
    sizeChart: {
      measurements: ['hips'],
      rows: [
        { size: 'XS', hips: 89 },
        { size: 'S', hips: 94 },
        { size: 'M', hips: 99 },
        { size: 'L', hips: 104 },
        { size: 'XL', hips: 109 },
      ],
    },
  },
];

export function getProductById(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}

export const CATEGORY_LABELS: Record<string, string> = {
  dresses: 'Dresses',
  tops: 'Tops',
  jeans: 'Jeans',
  skirts: 'Skirts',
};

export const FABRIC_STRETCH_LABELS: Record<string, string> = {
  none: 'No stretch',
  low: 'Low stretch',
  medium: 'Medium stretch',
  high: 'High stretch',
};

export const FIT_STYLE_LABELS: Record<string, string> = {
  fitted: 'Fitted',
  tailored: 'Tailored',
  relaxed: 'Relaxed',
  oversized: 'Oversized',
};
